# Generated by Django 3.2.10 on 2022-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('win', models.IntegerField(default=0)),
                ('Loss', models.IntegerField(default=0)),
                ('club', models.CharField(default='', max_length=50)),
                ('ranking', models.IntegerField(default=1)),
            ],
        ),
    ]
