# Generated by Django 3.2.10 on 2022-02-26 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fighter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 6, 46, 40, 681654)),
        ),
    ]
