# Generated by Django 3.2.10 on 2022-02-26 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 6, 47, 25, 785465, tzinfo=utc)),
        ),
    ]
