# Generated by Django 3.2.10 on 2022-02-26 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='promoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsor')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 6, 50, 44, 635905, tzinfo=utc)),
        ),
    ]
