# Generated by Django 3.2.10 on 2022-02-26 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220226_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='fights',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 16, 21, 44, 574125, tzinfo=utc)),
        ),
    ]
