# Generated by Django 3.2.10 on 2022-02-27 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220226_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='clubs')),
                ('location', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 13, 8, 18, 59155, tzinfo=utc)),
        ),
    ]
