# Generated by Django 3.2.10 on 2022-03-06 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220227_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 6, 9, 53, 0, 218212, tzinfo=utc))),
                ('age', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=40, unique=True)),
                ('coach', models.CharField(default='', max_length=40)),
                ('gym', models.CharField(default='', max_length=40)),
                ('frequency', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('uniqueId', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='promoters',
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 9, 53, 0, 187827, tzinfo=utc)),
        ),
    ]
