# Generated by Django 3.2.10 on 2022-03-06 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220306_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 10, 10, 37, 186219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 6, 10, 10, 37, 217224, tzinfo=utc)),
        ),
    ]
