# Generated by Django 3.2.10 on 2022-03-10 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220310_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homebanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('filename', models.ImageField(upload_to='sponsor')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 13, 56, 2, 903332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 13, 56, 2, 934580, tzinfo=utc)),
        ),
    ]
